### ISSUE TITLE
Redundant transform in prior class

### ISSUE THREAD

**Issue by xuyuon** [kazewong/jim#136]
Since we have added boundToUnbound transforms in sample transform, I think it is no longer necessary to build UniformPrior on top of a base distribution of LogisticDistribution. The only things from the prior class that are currently accessed in JIM are sample() and log_prob(), so as long as these two functions provide the correct output, the implementation details of the prior class under the hood are no longer important. We could simplify the implementation.

**Comment by kazewong** [comment]
I don't think we should abandon the prior implementation in PR #98. The reason is this provides the user with more guardrails on how to define a well-behaved prior. `BoundtoUnbound` is a transform, not a prior distribution. Rolling back this system will give room for more errors. Closing this issue unless there is a compelling argument for otherwise.
