### ISSUE TITLE
Add more prior classes and add composite prior example

### ISSUE THREAD

**Issue by kazewong** [kazewong/jim#41]
Currently there is only uniform prior with a guard outside the domain available.

This create issue of broken waveform returning nan when the gradient is large in HMC, which shoot the test point outside the domain and raising nan.

Here is a list of priors that could be useful to have:

- [x] Unconstrained uniform. Sample from an unconstrained distribution that corresponds to a uniform distribution over [a,b]
- [x] Uniform on sphere. Sample from a sphere and transform them into Cartesian coordinate. Useful for spins.
- [x] Add example of composite prior. This should take a list of priors and return a prior

**Comment by ThibeauWouters** [comment]
Peter and I were also interested in a DiracDelta prior, to fix e.g. the sky localisation to simplify the PE which might be useful to look into the sampling process itself and debug it. I haven't started on that, but that would also require a composite prior with some parameters having a uniform, and some having a DiracDelta prior. I'll ping u in case I start working on this at some point.

**Comment by ThibeauWouters** [comment]
Hi @kazewong , I was doing some PE runs on GW170817 and the luminosty distances are a bit off, because we are using the Uniform prior instead of a cosmological prior on the distance, as done in the TurboPE repo [here](https://github.com/kazewong/TurboPE/blob/main/src/scripts/run_GW170817.py). We were wondering, since you seemed to be working on prior classes, if it would be easy for you to add such a prior class to Jim? I am more than happy to help by implementing it myself in case you don't have time for it right now, but just wanted to check in case you are already working on something like this. Thanks a lot in advance!
